// Copyright (c) 2017-2023 VMware, Inc. or its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: cli_to_hub.proto

package idl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CliToHub_Initialize_FullMethodName              = "/idl.CliToHub/Initialize"
	CliToHub_InitializeCreateCluster_FullMethodName = "/idl.CliToHub/InitializeCreateCluster"
	CliToHub_Execute_FullMethodName                 = "/idl.CliToHub/Execute"
	CliToHub_Finalize_FullMethodName                = "/idl.CliToHub/Finalize"
	CliToHub_Revert_FullMethodName                  = "/idl.CliToHub/Revert"
	CliToHub_GetConfig_FullMethodName               = "/idl.CliToHub/GetConfig"
	CliToHub_RestartAgents_FullMethodName           = "/idl.CliToHub/RestartAgents"
	CliToHub_StopServices_FullMethodName            = "/idl.CliToHub/StopServices"
)

// CliToHubClient is the client API for CliToHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CliToHubClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error)
	InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error)
	Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (CliToHub_RevertClient, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error)
	StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error)
}

type cliToHubClient struct {
	cc grpc.ClientConnInterface
}

func NewCliToHubClient(cc grpc.ClientConnInterface) CliToHubClient {
	return &cliToHubClient{cc}
}

func (c *cliToHubClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error) {
	stream, err := c.cc.NewStream(ctx, &CliToHub_ServiceDesc.Streams[0], CliToHub_Initialize_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error) {
	stream, err := c.cc.NewStream(ctx, &CliToHub_ServiceDesc.Streams[1], CliToHub_InitializeCreateCluster_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeCreateClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeCreateClusterClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeCreateClusterClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeCreateClusterClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &CliToHub_ServiceDesc.Streams[2], CliToHub_Execute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_ExecuteClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubExecuteClient struct {
	grpc.ClientStream
}

func (x *cliToHubExecuteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &CliToHub_ServiceDesc.Streams[3], CliToHub_Finalize_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubFinalizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_FinalizeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubFinalizeClient struct {
	grpc.ClientStream
}

func (x *cliToHubFinalizeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (CliToHub_RevertClient, error) {
	stream, err := c.cc.NewStream(ctx, &CliToHub_ServiceDesc.Streams[4], CliToHub_Revert_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubRevertClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_RevertClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubRevertClient struct {
	grpc.ClientStream
}

func (x *cliToHubRevertClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, CliToHub_GetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error) {
	out := new(RestartAgentsReply)
	err := c.cc.Invoke(ctx, CliToHub_RestartAgents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error) {
	out := new(StopServicesReply)
	err := c.cc.Invoke(ctx, CliToHub_StopServices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CliToHubServer is the server API for CliToHub service.
// All implementations should embed UnimplementedCliToHubServer
// for forward compatibility
type CliToHubServer interface {
	Initialize(*InitializeRequest, CliToHub_InitializeServer) error
	InitializeCreateCluster(*InitializeCreateClusterRequest, CliToHub_InitializeCreateClusterServer) error
	Execute(*ExecuteRequest, CliToHub_ExecuteServer) error
	Finalize(*FinalizeRequest, CliToHub_FinalizeServer) error
	Revert(*RevertRequest, CliToHub_RevertServer) error
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	RestartAgents(context.Context, *RestartAgentsRequest) (*RestartAgentsReply, error)
	StopServices(context.Context, *StopServicesRequest) (*StopServicesReply, error)
}

// UnimplementedCliToHubServer should be embedded to have forward compatible implementations.
type UnimplementedCliToHubServer struct {
}

func (UnimplementedCliToHubServer) Initialize(*InitializeRequest, CliToHub_InitializeServer) error {
	return status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedCliToHubServer) InitializeCreateCluster(*InitializeCreateClusterRequest, CliToHub_InitializeCreateClusterServer) error {
	return status.Errorf(codes.Unimplemented, "method InitializeCreateCluster not implemented")
}
func (UnimplementedCliToHubServer) Execute(*ExecuteRequest, CliToHub_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCliToHubServer) Finalize(*FinalizeRequest, CliToHub_FinalizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedCliToHubServer) Revert(*RevertRequest, CliToHub_RevertServer) error {
	return status.Errorf(codes.Unimplemented, "method Revert not implemented")
}
func (UnimplementedCliToHubServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedCliToHubServer) RestartAgents(context.Context, *RestartAgentsRequest) (*RestartAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartAgents not implemented")
}
func (UnimplementedCliToHubServer) StopServices(context.Context, *StopServicesRequest) (*StopServicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServices not implemented")
}

// UnsafeCliToHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CliToHubServer will
// result in compilation errors.
type UnsafeCliToHubServer interface {
	mustEmbedUnimplementedCliToHubServer()
}

func RegisterCliToHubServer(s grpc.ServiceRegistrar, srv CliToHubServer) {
	s.RegisterService(&CliToHub_ServiceDesc, srv)
}

func _CliToHub_Initialize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Initialize(m, &cliToHubInitializeServer{stream})
}

type CliToHub_InitializeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_InitializeCreateCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeCreateClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).InitializeCreateCluster(m, &cliToHubInitializeCreateClusterServer{stream})
}

type CliToHub_InitializeCreateClusterServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeCreateClusterServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeCreateClusterServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Execute(m, &cliToHubExecuteServer{stream})
}

type CliToHub_ExecuteServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubExecuteServer struct {
	grpc.ServerStream
}

func (x *cliToHubExecuteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Finalize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FinalizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Finalize(m, &cliToHubFinalizeServer{stream})
}

type CliToHub_FinalizeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubFinalizeServer struct {
	grpc.ServerStream
}

func (x *cliToHubFinalizeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Revert_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RevertRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Revert(m, &cliToHubRevertServer{stream})
}

type CliToHub_RevertServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubRevertServer struct {
	grpc.ServerStream
}

func (x *cliToHubRevertServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CliToHub_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_RestartAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).RestartAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CliToHub_RestartAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).RestartAgents(ctx, req.(*RestartAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StopServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StopServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CliToHub_StopServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StopServices(ctx, req.(*StopServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CliToHub_ServiceDesc is the grpc.ServiceDesc for CliToHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CliToHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idl.CliToHub",
	HandlerType: (*CliToHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _CliToHub_GetConfig_Handler,
		},
		{
			MethodName: "RestartAgents",
			Handler:    _CliToHub_RestartAgents_Handler,
		},
		{
			MethodName: "StopServices",
			Handler:    _CliToHub_StopServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Initialize",
			Handler:       _CliToHub_Initialize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitializeCreateCluster",
			Handler:       _CliToHub_InitializeCreateCluster_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _CliToHub_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Finalize",
			Handler:       _CliToHub_Finalize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Revert",
			Handler:       _CliToHub_Revert_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cli_to_hub.proto",
}
