// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli_to_hub.proto

package idl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClusterDestination int32

const (
	ClusterDestination_unknown_destination ClusterDestination = 0
	ClusterDestination_source              ClusterDestination = 1
	ClusterDestination_intermediate        ClusterDestination = 2
	ClusterDestination_target              ClusterDestination = 3
)

var ClusterDestination_name = map[int32]string{
	0: "unknown_destination",
	1: "source",
	2: "intermediate",
	3: "target",
}

var ClusterDestination_value = map[string]int32{
	"unknown_destination": 0,
	"source":              1,
	"intermediate":        2,
	"target":              3,
}

func (x ClusterDestination) String() string {
	return proto.EnumName(ClusterDestination_name, int32(x))
}

func (ClusterDestination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{0}
}

type Step int32

const (
	Step_unknown_step Step = 0
	Step_initialize   Step = 1
	Step_execute      Step = 2
	Step_finalize     Step = 3
	Step_revert       Step = 4
	Step_stats        Step = 5
)

var Step_name = map[int32]string{
	0: "unknown_step",
	1: "initialize",
	2: "execute",
	3: "finalize",
	4: "revert",
	5: "stats",
}

var Step_value = map[string]int32{
	"unknown_step": 0,
	"initialize":   1,
	"execute":      2,
	"finalize":     3,
	"revert":       4,
	"stats":        5,
}

func (x Step) String() string {
	return proto.EnumName(Step_name, int32(x))
}

func (Step) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{1}
}

type Substep int32

const (
	Substep_unknown_substep                                               Substep = 0
	Substep_saving_source_cluster_config                                  Substep = 1
	Substep_start_hub                                                     Substep = 2
	Substep_start_agents                                                  Substep = 3
	Substep_check_environment                                             Substep = 4
	Substep_check_disk_space                                              Substep = 5
	Substep_generate_target_config                                        Substep = 6
	Substep_init_target_cluster                                           Substep = 7
	Substep_shutdown_target_cluster                                       Substep = 8
	Substep_backup_target_master                                          Substep = 9
	Substep_check_upgrade                                                 Substep = 10
	Substep_shutdown_source_cluster                                       Substep = 11
	Substep_upgrade_master                                                Substep = 12
	Substep_copy_master                                                   Substep = 13
	Substep_upgrade_primaries                                             Substep = 14
	Substep_start_target_cluster                                          Substep = 15
	Substep_update_target_catalog                                         Substep = 16
	Substep_update_data_directories                                       Substep = 17
	Substep_update_target_conf_files                                      Substep = 18
	Substep_upgrade_standby                                               Substep = 19
	Substep_upgrade_mirrors                                               Substep = 20
	Substep_delete_tablespaces                                            Substep = 21
	Substep_delete_target_cluster_datadirs                                Substep = 22
	Substep_delete_segment_statedirs                                      Substep = 23
	Substep_stop_hub_and_agents                                           Substep = 24
	Substep_delete_master_statedir                                        Substep = 25
	Substep_archive_log_directories                                       Substep = 26
	Substep_restore_source_cluster                                        Substep = 27
	Substep_start_source_cluster                                          Substep = 28
	Substep_restore_pgcontrol                                             Substep = 29
	Substep_recoverseg_source_cluster                                     Substep = 30
	Substep_step_status                                                   Substep = 31
	Substep_remove_source_mirrors                                         Substep = 32
	Substep_wait_for_cluster_to_be_ready_after_adding_mirrors_and_standby Substep = 33
	Substep_wait_for_cluster_to_be_ready_after_updating_catalog           Substep = 34
	Substep_stop_target_cluster                                           Substep = 35
	Substep_setting_dynamic_library_path_on_target_cluster                Substep = 36
	Substep_check_active_connections_on_source_cluster                    Substep = 37
	Substep_check_active_connections_on_target_cluster                    Substep = 38
	Substep_generate_data_migration_scripts                               Substep = 39
	Substep_execute_stats_data_migration_scripts                          Substep = 40
	Substep_execute_initialize_data_migration_scripts                     Substep = 41
	Substep_execute_finalize_data_migration_scripts                       Substep = 42
	Substep_execute_revert_data_migration_scripts                         Substep = 43
	Substep_create_backupdir                                              Substep = 44
	Substep_delete_backupdir                                              Substep = 45
)

var Substep_name = map[int32]string{
	0:  "unknown_substep",
	1:  "saving_source_cluster_config",
	2:  "start_hub",
	3:  "start_agents",
	4:  "check_environment",
	5:  "check_disk_space",
	6:  "generate_target_config",
	7:  "init_target_cluster",
	8:  "shutdown_target_cluster",
	9:  "backup_target_master",
	10: "check_upgrade",
	11: "shutdown_source_cluster",
	12: "upgrade_master",
	13: "copy_master",
	14: "upgrade_primaries",
	15: "start_target_cluster",
	16: "update_target_catalog",
	17: "update_data_directories",
	18: "update_target_conf_files",
	19: "upgrade_standby",
	20: "upgrade_mirrors",
	21: "delete_tablespaces",
	22: "delete_target_cluster_datadirs",
	23: "delete_segment_statedirs",
	24: "stop_hub_and_agents",
	25: "delete_master_statedir",
	26: "archive_log_directories",
	27: "restore_source_cluster",
	28: "start_source_cluster",
	29: "restore_pgcontrol",
	30: "recoverseg_source_cluster",
	31: "step_status",
	32: "remove_source_mirrors",
	33: "wait_for_cluster_to_be_ready_after_adding_mirrors_and_standby",
	34: "wait_for_cluster_to_be_ready_after_updating_catalog",
	35: "stop_target_cluster",
	36: "setting_dynamic_library_path_on_target_cluster",
	37: "check_active_connections_on_source_cluster",
	38: "check_active_connections_on_target_cluster",
	39: "generate_data_migration_scripts",
	40: "execute_stats_data_migration_scripts",
	41: "execute_initialize_data_migration_scripts",
	42: "execute_finalize_data_migration_scripts",
	43: "execute_revert_data_migration_scripts",
	44: "create_backupdir",
	45: "delete_backupdir",
}

var Substep_value = map[string]int32{
	"unknown_substep":                0,
	"saving_source_cluster_config":   1,
	"start_hub":                      2,
	"start_agents":                   3,
	"check_environment":              4,
	"check_disk_space":               5,
	"generate_target_config":         6,
	"init_target_cluster":            7,
	"shutdown_target_cluster":        8,
	"backup_target_master":           9,
	"check_upgrade":                  10,
	"shutdown_source_cluster":        11,
	"upgrade_master":                 12,
	"copy_master":                    13,
	"upgrade_primaries":              14,
	"start_target_cluster":           15,
	"update_target_catalog":          16,
	"update_data_directories":        17,
	"update_target_conf_files":       18,
	"upgrade_standby":                19,
	"upgrade_mirrors":                20,
	"delete_tablespaces":             21,
	"delete_target_cluster_datadirs": 22,
	"delete_segment_statedirs":       23,
	"stop_hub_and_agents":            24,
	"delete_master_statedir":         25,
	"archive_log_directories":        26,
	"restore_source_cluster":         27,
	"start_source_cluster":           28,
	"restore_pgcontrol":              29,
	"recoverseg_source_cluster":      30,
	"step_status":                    31,
	"remove_source_mirrors":          32,
	"wait_for_cluster_to_be_ready_after_adding_mirrors_and_standby": 33,
	"wait_for_cluster_to_be_ready_after_updating_catalog":           34,
	"stop_target_cluster":                            35,
	"setting_dynamic_library_path_on_target_cluster": 36,
	"check_active_connections_on_source_cluster":     37,
	"check_active_connections_on_target_cluster":     38,
	"generate_data_migration_scripts":                39,
	"execute_stats_data_migration_scripts":           40,
	"execute_initialize_data_migration_scripts":      41,
	"execute_finalize_data_migration_scripts":        42,
	"execute_revert_data_migration_scripts":          43,
	"create_backupdir":                               44,
	"delete_backupdir":                               45,
}

func (x Substep) String() string {
	return proto.EnumName(Substep_name, int32(x))
}

func (Substep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{2}
}

type Status int32

const (
	Status_unknown_status Status = 0
	Status_running        Status = 1
	Status_complete       Status = 2
	Status_failed         Status = 3
	Status_skipped        Status = 4
)

var Status_name = map[int32]string{
	0: "unknown_status",
	1: "running",
	2: "complete",
	3: "failed",
	4: "skipped",
}

var Status_value = map[string]int32{
	"unknown_status": 0,
	"running":        1,
	"complete":       2,
	"failed":         3,
	"skipped":        4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{3}
}

type Chunk_Type int32

const (
	Chunk_unknown Chunk_Type = 0
	Chunk_stdout  Chunk_Type = 1
	Chunk_stderr  Chunk_Type = 2
)

var Chunk_Type_name = map[int32]string{
	0: "unknown",
	1: "stdout",
	2: "stderr",
}

var Chunk_Type_value = map[string]int32{
	"unknown": 0,
	"stdout":  1,
	"stderr":  2,
}

func (x Chunk_Type) String() string {
	return proto.EnumName(Chunk_Type_name, int32(x))
}

func (Chunk_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{12, 0}
}

type InitializeRequest struct {
	AgentPort            int32    `protobuf:"varint,1,opt,name=agentPort,proto3" json:"agentPort,omitempty"`
	SourceGPHome         string   `protobuf:"bytes,2,opt,name=sourceGPHome,proto3" json:"sourceGPHome,omitempty"`
	TargetGPHome         string   `protobuf:"bytes,3,opt,name=targetGPHome,proto3" json:"targetGPHome,omitempty"`
	SourcePort           int32    `protobuf:"varint,4,opt,name=sourcePort,proto3" json:"sourcePort,omitempty"`
	LinkMode             bool     `protobuf:"varint,5,opt,name=linkMode,proto3" json:"linkMode,omitempty"`
	UseHbaHostnames      bool     `protobuf:"varint,6,opt,name=useHbaHostnames,proto3" json:"useHbaHostnames,omitempty"`
	Ports                []uint32 `protobuf:"varint,7,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	ParentBackupDir      string   `protobuf:"bytes,8,opt,name=parentBackupDir,proto3" json:"parentBackupDir,omitempty"`
	DiskFreeRatio        float64  `protobuf:"fixed64,9,opt,name=diskFreeRatio,proto3" json:"diskFreeRatio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{0}
}

func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (m *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(m, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

func (m *InitializeRequest) GetAgentPort() int32 {
	if m != nil {
		return m.AgentPort
	}
	return 0
}

func (m *InitializeRequest) GetSourceGPHome() string {
	if m != nil {
		return m.SourceGPHome
	}
	return ""
}

func (m *InitializeRequest) GetTargetGPHome() string {
	if m != nil {
		return m.TargetGPHome
	}
	return ""
}

func (m *InitializeRequest) GetSourcePort() int32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *InitializeRequest) GetLinkMode() bool {
	if m != nil {
		return m.LinkMode
	}
	return false
}

func (m *InitializeRequest) GetUseHbaHostnames() bool {
	if m != nil {
		return m.UseHbaHostnames
	}
	return false
}

func (m *InitializeRequest) GetPorts() []uint32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *InitializeRequest) GetParentBackupDir() string {
	if m != nil {
		return m.ParentBackupDir
	}
	return ""
}

func (m *InitializeRequest) GetDiskFreeRatio() float64 {
	if m != nil {
		return m.DiskFreeRatio
	}
	return 0
}

type InitializeCreateClusterRequest struct {
	DynamicLibraryPath   string   `protobuf:"bytes,1,opt,name=dynamicLibraryPath,proto3" json:"dynamicLibraryPath,omitempty"`
	PgUpgradeVerbose     bool     `protobuf:"varint,2,opt,name=pgUpgradeVerbose,proto3" json:"pgUpgradeVerbose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeCreateClusterRequest) Reset()         { *m = InitializeCreateClusterRequest{} }
func (m *InitializeCreateClusterRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeCreateClusterRequest) ProtoMessage()    {}
func (*InitializeCreateClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{1}
}

func (m *InitializeCreateClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeCreateClusterRequest.Unmarshal(m, b)
}
func (m *InitializeCreateClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeCreateClusterRequest.Marshal(b, m, deterministic)
}
func (m *InitializeCreateClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeCreateClusterRequest.Merge(m, src)
}
func (m *InitializeCreateClusterRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeCreateClusterRequest.Size(m)
}
func (m *InitializeCreateClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeCreateClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeCreateClusterRequest proto.InternalMessageInfo

func (m *InitializeCreateClusterRequest) GetDynamicLibraryPath() string {
	if m != nil {
		return m.DynamicLibraryPath
	}
	return ""
}

func (m *InitializeCreateClusterRequest) GetPgUpgradeVerbose() bool {
	if m != nil {
		return m.PgUpgradeVerbose
	}
	return false
}

type ExecuteRequest struct {
	PgUpgradeVerbose     bool     `protobuf:"varint,1,opt,name=pgUpgradeVerbose,proto3" json:"pgUpgradeVerbose,omitempty"`
	ParentBackupDir      string   `protobuf:"bytes,2,opt,name=parentBackupDir,proto3" json:"parentBackupDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{2}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetPgUpgradeVerbose() bool {
	if m != nil {
		return m.PgUpgradeVerbose
	}
	return false
}

func (m *ExecuteRequest) GetParentBackupDir() string {
	if m != nil {
		return m.ParentBackupDir
	}
	return ""
}

type FinalizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{3}
}

func (m *FinalizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeRequest.Unmarshal(m, b)
}
func (m *FinalizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeRequest.Marshal(b, m, deterministic)
}
func (m *FinalizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeRequest.Merge(m, src)
}
func (m *FinalizeRequest) XXX_Size() int {
	return xxx_messageInfo_FinalizeRequest.Size(m)
}
func (m *FinalizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeRequest proto.InternalMessageInfo

type RevertRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevertRequest) Reset()         { *m = RevertRequest{} }
func (m *RevertRequest) String() string { return proto.CompactTextString(m) }
func (*RevertRequest) ProtoMessage()    {}
func (*RevertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{4}
}

func (m *RevertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevertRequest.Unmarshal(m, b)
}
func (m *RevertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevertRequest.Marshal(b, m, deterministic)
}
func (m *RevertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevertRequest.Merge(m, src)
}
func (m *RevertRequest) XXX_Size() int {
	return xxx_messageInfo_RevertRequest.Size(m)
}
func (m *RevertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevertRequest proto.InternalMessageInfo

type RestartAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsRequest) Reset()         { *m = RestartAgentsRequest{} }
func (m *RestartAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsRequest) ProtoMessage()    {}
func (*RestartAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{5}
}

func (m *RestartAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsRequest.Unmarshal(m, b)
}
func (m *RestartAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsRequest.Marshal(b, m, deterministic)
}
func (m *RestartAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsRequest.Merge(m, src)
}
func (m *RestartAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsRequest.Size(m)
}
func (m *RestartAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsRequest proto.InternalMessageInfo

type RestartAgentsReply struct {
	AgentHosts           []string `protobuf:"bytes,1,rep,name=agentHosts,proto3" json:"agentHosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsReply) Reset()         { *m = RestartAgentsReply{} }
func (m *RestartAgentsReply) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsReply) ProtoMessage()    {}
func (*RestartAgentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{6}
}

func (m *RestartAgentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsReply.Unmarshal(m, b)
}
func (m *RestartAgentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsReply.Marshal(b, m, deterministic)
}
func (m *RestartAgentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsReply.Merge(m, src)
}
func (m *RestartAgentsReply) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsReply.Size(m)
}
func (m *RestartAgentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsReply proto.InternalMessageInfo

func (m *RestartAgentsReply) GetAgentHosts() []string {
	if m != nil {
		return m.AgentHosts
	}
	return nil
}

type StopServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesRequest) Reset()         { *m = StopServicesRequest{} }
func (m *StopServicesRequest) String() string { return proto.CompactTextString(m) }
func (*StopServicesRequest) ProtoMessage()    {}
func (*StopServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{7}
}

func (m *StopServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesRequest.Unmarshal(m, b)
}
func (m *StopServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesRequest.Marshal(b, m, deterministic)
}
func (m *StopServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesRequest.Merge(m, src)
}
func (m *StopServicesRequest) XXX_Size() int {
	return xxx_messageInfo_StopServicesRequest.Size(m)
}
func (m *StopServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesRequest proto.InternalMessageInfo

type StopServicesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesReply) Reset()         { *m = StopServicesReply{} }
func (m *StopServicesReply) String() string { return proto.CompactTextString(m) }
func (*StopServicesReply) ProtoMessage()    {}
func (*StopServicesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{8}
}

func (m *StopServicesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesReply.Unmarshal(m, b)
}
func (m *StopServicesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesReply.Marshal(b, m, deterministic)
}
func (m *StopServicesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesReply.Merge(m, src)
}
func (m *StopServicesReply) XXX_Size() int {
	return xxx_messageInfo_StopServicesReply.Size(m)
}
func (m *StopServicesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesReply proto.InternalMessageInfo

type SubstepStatus struct {
	Step                 Substep  `protobuf:"varint,1,opt,name=step,proto3,enum=idl.Substep" json:"step,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=idl.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubstepStatus) Reset()         { *m = SubstepStatus{} }
func (m *SubstepStatus) String() string { return proto.CompactTextString(m) }
func (*SubstepStatus) ProtoMessage()    {}
func (*SubstepStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{9}
}

func (m *SubstepStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubstepStatus.Unmarshal(m, b)
}
func (m *SubstepStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubstepStatus.Marshal(b, m, deterministic)
}
func (m *SubstepStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubstepStatus.Merge(m, src)
}
func (m *SubstepStatus) XXX_Size() int {
	return xxx_messageInfo_SubstepStatus.Size(m)
}
func (m *SubstepStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SubstepStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SubstepStatus proto.InternalMessageInfo

func (m *SubstepStatus) GetStep() Substep {
	if m != nil {
		return m.Step
	}
	return Substep_unknown_substep
}

func (m *SubstepStatus) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_unknown_status
}

type PrepareInitClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterRequest) Reset()         { *m = PrepareInitClusterRequest{} }
func (m *PrepareInitClusterRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterRequest) ProtoMessage()    {}
func (*PrepareInitClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{10}
}

func (m *PrepareInitClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterRequest.Unmarshal(m, b)
}
func (m *PrepareInitClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterRequest.Marshal(b, m, deterministic)
}
func (m *PrepareInitClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterRequest.Merge(m, src)
}
func (m *PrepareInitClusterRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterRequest.Size(m)
}
func (m *PrepareInitClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterRequest proto.InternalMessageInfo

type PrepareInitClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterReply) Reset()         { *m = PrepareInitClusterReply{} }
func (m *PrepareInitClusterReply) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterReply) ProtoMessage()    {}
func (*PrepareInitClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{11}
}

func (m *PrepareInitClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterReply.Unmarshal(m, b)
}
func (m *PrepareInitClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterReply.Marshal(b, m, deterministic)
}
func (m *PrepareInitClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterReply.Merge(m, src)
}
func (m *PrepareInitClusterReply) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterReply.Size(m)
}
func (m *PrepareInitClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterReply proto.InternalMessageInfo

type Chunk struct {
	Buffer               []byte     `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Type                 Chunk_Type `protobuf:"varint,2,opt,name=type,proto3,enum=idl.Chunk_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{12}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *Chunk) GetType() Chunk_Type {
	if m != nil {
		return m.Type
	}
	return Chunk_unknown
}

type Message struct {
	// Types that are valid to be assigned to Contents:
	//	*Message_Chunk
	//	*Message_Status
	//	*Message_Response
	Contents             isMessage_Contents `protobuf_oneof:"contents"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{13}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Contents interface {
	isMessage_Contents()
}

type Message_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type Message_Status struct {
	Status *SubstepStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type Message_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*Message_Chunk) isMessage_Contents() {}

func (*Message_Status) isMessage_Contents() {}

func (*Message_Response) isMessage_Contents() {}

func (m *Message) GetContents() isMessage_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Message) GetChunk() *Chunk {
	if x, ok := m.GetContents().(*Message_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *Message) GetStatus() *SubstepStatus {
	if x, ok := m.GetContents().(*Message_Status); ok {
		return x.Status
	}
	return nil
}

func (m *Message) GetResponse() *Response {
	if x, ok := m.GetContents().(*Message_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Chunk)(nil),
		(*Message_Status)(nil),
		(*Message_Response)(nil),
	}
}

type Response struct {
	// Types that are valid to be assigned to Contents:
	//	*Response_InitializeResponse
	//	*Response_ExecuteResponse
	//	*Response_FinalizeResponse
	//	*Response_RevertResponse
	Contents             isResponse_Contents `protobuf_oneof:"contents"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{14}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Contents interface {
	isResponse_Contents()
}

type Response_InitializeResponse struct {
	InitializeResponse *InitializeResponse `protobuf:"bytes,3,opt,name=initializeResponse,proto3,oneof"`
}

type Response_ExecuteResponse struct {
	ExecuteResponse *ExecuteResponse `protobuf:"bytes,4,opt,name=executeResponse,proto3,oneof"`
}

type Response_FinalizeResponse struct {
	FinalizeResponse *FinalizeResponse `protobuf:"bytes,5,opt,name=finalizeResponse,proto3,oneof"`
}

type Response_RevertResponse struct {
	RevertResponse *RevertResponse `protobuf:"bytes,6,opt,name=revertResponse,proto3,oneof"`
}

func (*Response_InitializeResponse) isResponse_Contents() {}

func (*Response_ExecuteResponse) isResponse_Contents() {}

func (*Response_FinalizeResponse) isResponse_Contents() {}

func (*Response_RevertResponse) isResponse_Contents() {}

func (m *Response) GetContents() isResponse_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Response) GetInitializeResponse() *InitializeResponse {
	if x, ok := m.GetContents().(*Response_InitializeResponse); ok {
		return x.InitializeResponse
	}
	return nil
}

func (m *Response) GetExecuteResponse() *ExecuteResponse {
	if x, ok := m.GetContents().(*Response_ExecuteResponse); ok {
		return x.ExecuteResponse
	}
	return nil
}

func (m *Response) GetFinalizeResponse() *FinalizeResponse {
	if x, ok := m.GetContents().(*Response_FinalizeResponse); ok {
		return x.FinalizeResponse
	}
	return nil
}

func (m *Response) GetRevertResponse() *RevertResponse {
	if x, ok := m.GetContents().(*Response_RevertResponse); ok {
		return x.RevertResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_InitializeResponse)(nil),
		(*Response_ExecuteResponse)(nil),
		(*Response_FinalizeResponse)(nil),
		(*Response_RevertResponse)(nil),
	}
}

type InitializeResponse struct {
	HasAllMirrorsAndStandby bool     `protobuf:"varint,1,opt,name=HasAllMirrorsAndStandby,proto3" json:"HasAllMirrorsAndStandby,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *InitializeResponse) Reset()         { *m = InitializeResponse{} }
func (m *InitializeResponse) String() string { return proto.CompactTextString(m) }
func (*InitializeResponse) ProtoMessage()    {}
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{15}
}

func (m *InitializeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeResponse.Unmarshal(m, b)
}
func (m *InitializeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeResponse.Marshal(b, m, deterministic)
}
func (m *InitializeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeResponse.Merge(m, src)
}
func (m *InitializeResponse) XXX_Size() int {
	return xxx_messageInfo_InitializeResponse.Size(m)
}
func (m *InitializeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeResponse proto.InternalMessageInfo

func (m *InitializeResponse) GetHasAllMirrorsAndStandby() bool {
	if m != nil {
		return m.HasAllMirrorsAndStandby
	}
	return false
}

type Cluster struct {
	GPHome                   string   `protobuf:"bytes,1,opt,name=GPHome,proto3" json:"GPHome,omitempty"`
	CoordinatorDataDirectory string   `protobuf:"bytes,2,opt,name=CoordinatorDataDirectory,proto3" json:"CoordinatorDataDirectory,omitempty"`
	Port                     int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{16}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetGPHome() string {
	if m != nil {
		return m.GPHome
	}
	return ""
}

func (m *Cluster) GetCoordinatorDataDirectory() string {
	if m != nil {
		return m.CoordinatorDataDirectory
	}
	return ""
}

func (m *Cluster) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ExecuteResponse struct {
	Target               *Cluster `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{17}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetTarget() *Cluster {
	if m != nil {
		return m.Target
	}
	return nil
}

type FinalizeResponse struct {
	TargetCluster                          *Cluster `protobuf:"bytes,1,opt,name=TargetCluster,proto3" json:"TargetCluster,omitempty"`
	TargetVersion                          string   `protobuf:"bytes,2,opt,name=TargetVersion,proto3" json:"TargetVersion,omitempty"`
	LogArchiveDirectory                    string   `protobuf:"bytes,3,opt,name=LogArchiveDirectory,proto3" json:"LogArchiveDirectory,omitempty"`
	ArchivedSourceCoordinatorDataDirectory string   `protobuf:"bytes,4,opt,name=ArchivedSourceCoordinatorDataDirectory,proto3" json:"ArchivedSourceCoordinatorDataDirectory,omitempty"`
	UpgradeID                              string   `protobuf:"bytes,5,opt,name=UpgradeID,proto3" json:"UpgradeID,omitempty"`
	XXX_NoUnkeyedLiteral                   struct{} `json:"-"`
	XXX_unrecognized                       []byte   `json:"-"`
	XXX_sizecache                          int32    `json:"-"`
}

func (m *FinalizeResponse) Reset()         { *m = FinalizeResponse{} }
func (m *FinalizeResponse) String() string { return proto.CompactTextString(m) }
func (*FinalizeResponse) ProtoMessage()    {}
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{18}
}

func (m *FinalizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeResponse.Unmarshal(m, b)
}
func (m *FinalizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeResponse.Marshal(b, m, deterministic)
}
func (m *FinalizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeResponse.Merge(m, src)
}
func (m *FinalizeResponse) XXX_Size() int {
	return xxx_messageInfo_FinalizeResponse.Size(m)
}
func (m *FinalizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeResponse proto.InternalMessageInfo

func (m *FinalizeResponse) GetTargetCluster() *Cluster {
	if m != nil {
		return m.TargetCluster
	}
	return nil
}

func (m *FinalizeResponse) GetTargetVersion() string {
	if m != nil {
		return m.TargetVersion
	}
	return ""
}

func (m *FinalizeResponse) GetLogArchiveDirectory() string {
	if m != nil {
		return m.LogArchiveDirectory
	}
	return ""
}

func (m *FinalizeResponse) GetArchivedSourceCoordinatorDataDirectory() string {
	if m != nil {
		return m.ArchivedSourceCoordinatorDataDirectory
	}
	return ""
}

func (m *FinalizeResponse) GetUpgradeID() string {
	if m != nil {
		return m.UpgradeID
	}
	return ""
}

type RevertResponse struct {
	Source               *Cluster `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	SourceVersion        string   `protobuf:"bytes,2,opt,name=SourceVersion,proto3" json:"SourceVersion,omitempty"`
	LogArchiveDirectory  string   `protobuf:"bytes,3,opt,name=LogArchiveDirectory,proto3" json:"LogArchiveDirectory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevertResponse) Reset()         { *m = RevertResponse{} }
func (m *RevertResponse) String() string { return proto.CompactTextString(m) }
func (*RevertResponse) ProtoMessage()    {}
func (*RevertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{19}
}

func (m *RevertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevertResponse.Unmarshal(m, b)
}
func (m *RevertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevertResponse.Marshal(b, m, deterministic)
}
func (m *RevertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevertResponse.Merge(m, src)
}
func (m *RevertResponse) XXX_Size() int {
	return xxx_messageInfo_RevertResponse.Size(m)
}
func (m *RevertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevertResponse proto.InternalMessageInfo

func (m *RevertResponse) GetSource() *Cluster {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *RevertResponse) GetSourceVersion() string {
	if m != nil {
		return m.SourceVersion
	}
	return ""
}

func (m *RevertResponse) GetLogArchiveDirectory() string {
	if m != nil {
		return m.LogArchiveDirectory
	}
	return ""
}

type GetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{20}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{21}
}

func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (m *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(m, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Used to set the gRPC status details that the CLI converts to a NextActions
// error type to be displayed to the user.
type NextActions struct {
	NextActions          string   `protobuf:"bytes,1,opt,name=nextActions,proto3" json:"nextActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextActions) Reset()         { *m = NextActions{} }
func (m *NextActions) String() string { return proto.CompactTextString(m) }
func (*NextActions) ProtoMessage()    {}
func (*NextActions) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{22}
}

func (m *NextActions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextActions.Unmarshal(m, b)
}
func (m *NextActions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextActions.Marshal(b, m, deterministic)
}
func (m *NextActions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextActions.Merge(m, src)
}
func (m *NextActions) XXX_Size() int {
	return xxx_messageInfo_NextActions.Size(m)
}
func (m *NextActions) XXX_DiscardUnknown() {
	xxx_messageInfo_NextActions.DiscardUnknown(m)
}

var xxx_messageInfo_NextActions proto.InternalMessageInfo

func (m *NextActions) GetNextActions() string {
	if m != nil {
		return m.NextActions
	}
	return ""
}

func init() {
	proto.RegisterEnum("idl.ClusterDestination", ClusterDestination_name, ClusterDestination_value)
	proto.RegisterEnum("idl.Step", Step_name, Step_value)
	proto.RegisterEnum("idl.Substep", Substep_name, Substep_value)
	proto.RegisterEnum("idl.Status", Status_name, Status_value)
	proto.RegisterEnum("idl.Chunk_Type", Chunk_Type_name, Chunk_Type_value)
	proto.RegisterType((*InitializeRequest)(nil), "idl.InitializeRequest")
	proto.RegisterType((*InitializeCreateClusterRequest)(nil), "idl.InitializeCreateClusterRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "idl.ExecuteRequest")
	proto.RegisterType((*FinalizeRequest)(nil), "idl.FinalizeRequest")
	proto.RegisterType((*RevertRequest)(nil), "idl.RevertRequest")
	proto.RegisterType((*RestartAgentsRequest)(nil), "idl.RestartAgentsRequest")
	proto.RegisterType((*RestartAgentsReply)(nil), "idl.RestartAgentsReply")
	proto.RegisterType((*StopServicesRequest)(nil), "idl.StopServicesRequest")
	proto.RegisterType((*StopServicesReply)(nil), "idl.StopServicesReply")
	proto.RegisterType((*SubstepStatus)(nil), "idl.SubstepStatus")
	proto.RegisterType((*PrepareInitClusterRequest)(nil), "idl.PrepareInitClusterRequest")
	proto.RegisterType((*PrepareInitClusterReply)(nil), "idl.PrepareInitClusterReply")
	proto.RegisterType((*Chunk)(nil), "idl.Chunk")
	proto.RegisterType((*Message)(nil), "idl.Message")
	proto.RegisterType((*Response)(nil), "idl.Response")
	proto.RegisterType((*InitializeResponse)(nil), "idl.InitializeResponse")
	proto.RegisterType((*Cluster)(nil), "idl.Cluster")
	proto.RegisterType((*ExecuteResponse)(nil), "idl.ExecuteResponse")
	proto.RegisterType((*FinalizeResponse)(nil), "idl.FinalizeResponse")
	proto.RegisterType((*RevertResponse)(nil), "idl.RevertResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "idl.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "idl.GetConfigReply")
	proto.RegisterType((*NextActions)(nil), "idl.NextActions")
}

func init() { proto.RegisterFile("cli_to_hub.proto", fileDescriptor_631e66a01873be02) }

var fileDescriptor_631e66a01873be02 = []byte{
	// 1806 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xeb, 0x6e, 0x1b, 0xc7,
	0x15, 0x26, 0x45, 0x52, 0x22, 0x8f, 0x6e, 0xa3, 0xa3, 0x1b, 0x25, 0x3b, 0x8e, 0xba, 0x72, 0x1c,
	0x59, 0x4e, 0x54, 0x43, 0x29, 0x9a, 0xb6, 0x40, 0x80, 0xca, 0x92, 0x1d, 0x1a, 0x88, 0x03, 0x61,
	0xe5, 0xba, 0x40, 0xff, 0x2c, 0x86, 0xbb, 0x43, 0x6a, 0xa0, 0xe5, 0xce, 0x7a, 0x66, 0xa8, 0x84,
	0x45, 0x9f, 0xa1, 0xbf, 0xf2, 0x0e, 0x7d, 0x92, 0x3e, 0x4f, 0xfb, 0x08, 0xc5, 0x5c, 0x96, 0x97,
	0x15, 0x89, 0x3a, 0xff, 0xb8, 0xe7, 0x7c, 0x73, 0x66, 0xe6, 0x3b, 0x67, 0xbe, 0x39, 0x43, 0x20,
	0x71, 0xca, 0x23, 0x2d, 0xa2, 0xdb, 0x61, 0xf7, 0x2c, 0x97, 0x42, 0x0b, 0xac, 0xf1, 0x24, 0x0d,
	0xfe, 0xbd, 0x04, 0x5b, 0x6f, 0x33, 0xae, 0x39, 0x4d, 0xf9, 0xdf, 0x59, 0xc8, 0x3e, 0x0e, 0x99,
	0xd2, 0xf8, 0x18, 0x5a, 0xb4, 0xcf, 0x32, 0x7d, 0x2d, 0xa4, 0x6e, 0x57, 0x8f, 0xaa, 0x27, 0x8d,
	0x70, 0x62, 0xc0, 0x00, 0xd6, 0x94, 0x18, 0xca, 0x98, 0x7d, 0x7f, 0xdd, 0x11, 0x03, 0xd6, 0x5e,
	0x3a, 0xaa, 0x9e, 0xb4, 0xc2, 0x19, 0x9b, 0xc1, 0x68, 0x2a, 0xfb, 0x4c, 0x7b, 0x4c, 0xcd, 0x61,
	0xa6, 0x6d, 0xf8, 0x04, 0xc0, 0x8d, 0xb1, 0xd3, 0xd4, 0xed, 0x34, 0x53, 0x16, 0x3c, 0x84, 0x66,
	0xca, 0xb3, 0xbb, 0x77, 0x22, 0x61, 0xed, 0xc6, 0x51, 0xf5, 0xa4, 0x19, 0x8e, 0xbf, 0xf1, 0x04,
	0x36, 0x87, 0x8a, 0x75, 0xba, 0xb4, 0x23, 0x94, 0xce, 0xe8, 0x80, 0xa9, 0xf6, 0xb2, 0x85, 0x94,
	0xcd, 0xb8, 0x03, 0x8d, 0x5c, 0x48, 0xad, 0xda, 0x2b, 0x47, 0xb5, 0x93, 0xf5, 0xd0, 0x7d, 0x98,
	0xf1, 0x39, 0x95, 0x2c, 0xd3, 0xaf, 0x68, 0x7c, 0x37, 0xcc, 0xaf, 0xb8, 0x6c, 0x37, 0xed, 0x12,
	0xcb, 0x66, 0x7c, 0x0a, 0xeb, 0x09, 0x57, 0x77, 0x6f, 0x24, 0x63, 0x21, 0xd5, 0x5c, 0xb4, 0x5b,
	0x47, 0xd5, 0x93, 0x6a, 0x38, 0x6b, 0x0c, 0xfe, 0x01, 0x4f, 0x26, 0x34, 0x5e, 0x4a, 0x46, 0x35,
	0xbb, 0x4c, 0x87, 0x4a, 0x33, 0x59, 0x70, 0x7a, 0x06, 0x98, 0x8c, 0x32, 0x3a, 0xe0, 0xf1, 0x0f,
	0xbc, 0x2b, 0xa9, 0x1c, 0x5d, 0x53, 0x7d, 0x6b, 0xc9, 0x6d, 0x85, 0x73, 0x3c, 0x78, 0x0a, 0x24,
	0xef, 0xff, 0x25, 0xef, 0x4b, 0x9a, 0xb0, 0x0f, 0x4c, 0x76, 0x85, 0x72, 0x4c, 0x37, 0xc3, 0x07,
	0xf6, 0xa0, 0x07, 0x1b, 0xaf, 0x7f, 0x66, 0xf1, 0x50, 0x8f, 0x33, 0x38, 0x6f, 0x74, 0x75, 0xfe,
	0xe8, 0x79, 0x5c, 0x2c, 0xcd, 0xe5, 0x22, 0xd8, 0x82, 0xcd, 0x37, 0x3c, 0x9b, 0x2e, 0x95, 0x60,
	0x13, 0xd6, 0x43, 0x76, 0xcf, 0xa4, 0x2e, 0x0c, 0x7b, 0xb0, 0x13, 0x32, 0xa5, 0xa9, 0xd4, 0x17,
	0xa6, 0x62, 0x54, 0x61, 0xff, 0x1d, 0x60, 0xc9, 0x9e, 0xa7, 0x23, 0x53, 0x03, 0xb6, 0xb0, 0x4c,
	0xbe, 0x54, 0xbb, 0x7a, 0x54, 0x3b, 0x69, 0x85, 0x53, 0x96, 0x60, 0x17, 0xb6, 0x6f, 0xb4, 0xc8,
	0x6f, 0x98, 0xbc, 0xe7, 0x31, 0x1b, 0x07, 0xdb, 0x86, 0xad, 0x59, 0x73, 0x9e, 0x8e, 0x82, 0x0f,
	0xb0, 0x7e, 0x33, 0xec, 0x2a, 0xcd, 0xf2, 0x1b, 0x4d, 0xf5, 0x50, 0xe1, 0x11, 0xd4, 0xcd, 0x97,
	0xdd, 0xf8, 0xc6, 0xf9, 0xda, 0x19, 0x4f, 0xd2, 0x33, 0x8f, 0x08, 0xad, 0x07, 0x8f, 0x61, 0x59,
	0x59, 0xac, 0xdd, 0xf1, 0xc6, 0xf9, 0xaa, 0xc3, 0x58, 0x53, 0xe8, 0x5d, 0xc1, 0x23, 0x38, 0xb8,
	0x96, 0xcc, 0x70, 0x61, 0x52, 0x3c, 0x9b, 0xd6, 0xe0, 0x00, 0xf6, 0xe7, 0x39, 0xcd, 0x7a, 0x3e,
	0x42, 0xe3, 0xf2, 0x76, 0x98, 0xdd, 0xe1, 0x1e, 0x2c, 0x77, 0x87, 0xbd, 0x1e, 0x93, 0x76, 0x25,
	0x6b, 0xa1, 0xff, 0xc2, 0x63, 0xa8, 0xeb, 0x51, 0xce, 0xfc, 0xdc, 0x9b, 0x76, 0x6e, 0x3b, 0xe2,
	0xec, 0xfd, 0x28, 0x67, 0xa1, 0x75, 0x06, 0x2f, 0xa0, 0x6e, 0xbe, 0x70, 0x15, 0x56, 0x86, 0xd9,
	0x5d, 0x26, 0x7e, 0xca, 0x48, 0x05, 0xc1, 0xac, 0x3b, 0x11, 0x43, 0x4d, 0xaa, 0xfe, 0x37, 0x93,
	0x92, 0x2c, 0x05, 0xbf, 0x54, 0x61, 0xe5, 0x1d, 0x53, 0x8a, 0xf6, 0xcd, 0x11, 0x6c, 0xc4, 0x26,
	0x98, 0x9d, 0x74, 0xf5, 0x1c, 0x26, 0xe1, 0x3b, 0x95, 0xd0, 0xb9, 0xf0, 0xab, 0x99, 0xfd, 0xaf,
	0x9e, 0xe3, 0x34, 0x47, 0x8e, 0x86, 0x4e, 0xa5, 0x20, 0x02, 0x5f, 0x40, 0x53, 0x32, 0x95, 0x8b,
	0x4c, 0xb9, 0x03, 0xbd, 0x7a, 0xbe, 0x6e, 0xf1, 0xa1, 0x37, 0x76, 0x2a, 0xe1, 0x18, 0xf0, 0x0a,
	0xa0, 0x19, 0x8b, 0x4c, 0x9b, 0x54, 0x07, 0xff, 0x5a, 0x82, 0x66, 0x01, 0xc2, 0xb7, 0x80, 0x7c,
	0x4a, 0x71, 0x66, 0xe2, 0xed, 0xdb, 0x78, 0x6f, 0x1f, 0xb8, 0x3b, 0x95, 0x70, 0xce, 0x20, 0xfc,
	0x33, 0x6c, 0xb2, 0xa2, 0xee, 0x7d, 0x9c, 0xba, 0x8d, 0xb3, 0x63, 0xe3, 0xbc, 0x9e, 0xf5, 0x75,
	0x2a, 0x61, 0x19, 0x8e, 0x97, 0x40, 0x7a, 0xe3, 0x8a, 0xf6, 0x21, 0x1a, 0x36, 0xc4, 0xae, 0x0d,
	0xf1, 0xa6, 0xe4, 0xec, 0x54, 0xc2, 0x07, 0x03, 0xf0, 0x3b, 0xd8, 0x90, 0xfe, 0x0c, 0xf8, 0x10,
	0xcb, 0x36, 0xc4, 0xb6, 0x67, 0x67, 0xda, 0xd5, 0xa9, 0x84, 0x25, 0xf0, 0x0c, 0x53, 0x3f, 0x02,
	0x3e, 0xdc, 0x3d, 0xfe, 0x01, 0xf6, 0x3b, 0x54, 0x5d, 0xa4, 0xe9, 0x3b, 0x2e, 0xa5, 0x90, 0xea,
	0x22, 0x4b, 0x6e, 0x34, 0xcd, 0x92, 0xee, 0xc8, 0x1f, 0xea, 0x45, 0xee, 0xe0, 0x23, 0xac, 0xf8,
	0x9a, 0x34, 0x55, 0xe8, 0xc5, 0xd8, 0x89, 0x8e, 0xff, 0xc2, 0x3f, 0x41, 0xfb, 0x52, 0x08, 0x99,
	0xf0, 0x8c, 0x6a, 0x21, 0xaf, 0xa8, 0xa6, 0x57, 0x5c, 0xb2, 0x58, 0x0b, 0x39, 0xf2, 0x3a, 0xb0,
	0xd0, 0x8f, 0x08, 0x75, 0x2b, 0xde, 0x35, 0x2b, 0xde, 0xf6, 0x77, 0xf0, 0x2d, 0x6c, 0x96, 0x88,
	0xc7, 0xa7, 0xb0, 0xec, 0x94, 0xdf, 0xd7, 0xa2, 0x3b, 0x8a, 0xc5, 0x61, 0xf1, 0xbe, 0xe0, 0x97,
	0x25, 0x20, 0x65, 0xbe, 0xf1, 0x1c, 0xd6, 0xdf, 0x5b, 0xb7, 0x47, 0xcf, 0x8d, 0x30, 0x0b, 0x31,
	0x92, 0xed, 0x0c, 0x1f, 0x98, 0x54, 0x5c, 0x64, 0x7e, 0x1b, 0xb3, 0x46, 0x7c, 0x09, 0xdb, 0x3f,
	0x88, 0xfe, 0x85, 0x8c, 0x6f, 0xf9, 0x3d, 0x9b, 0x6c, 0xd9, 0xdd, 0x54, 0xf3, 0x5c, 0xf8, 0x01,
	0x9e, 0x79, 0x5b, 0x72, 0x63, 0xaf, 0xa9, 0x85, 0xbc, 0xd5, 0x6d, 0x90, 0x4f, 0x44, 0x9b, 0xeb,
	0xd6, 0x4b, 0xf2, 0xdb, 0x2b, 0x5b, 0x7d, 0xad, 0x70, 0x62, 0x08, 0xfe, 0x59, 0x85, 0x8d, 0xd9,
	0x1a, 0x32, 0x7c, 0xba, 0x7b, 0x72, 0x3e, 0x9f, 0xce, 0x67, 0x68, 0x70, 0x13, 0x97, 0x68, 0x98,
	0x31, 0xfe, 0x7a, 0x1a, 0x82, 0x67, 0x40, 0xbe, 0x67, 0xfa, 0x52, 0x64, 0x3d, 0xde, 0x2f, 0xee,
	0x1b, 0x84, 0xba, 0xb9, 0x6e, 0x7d, 0x69, 0xd9, 0xdf, 0xc1, 0x33, 0xd8, 0x98, 0xc2, 0x19, 0xb5,
	0xdf, 0x81, 0xc6, 0x3d, 0x4d, 0x87, 0x05, 0xcc, 0x7d, 0x04, 0xbf, 0x85, 0xd5, 0x1f, 0xd9, 0xcf,
	0xfa, 0x22, 0xd6, 0x5c, 0x64, 0x46, 0xb5, 0x57, 0xb3, 0xc9, 0xa7, 0x87, 0x4e, 0x9b, 0x4e, 0xff,
	0x0a, 0xe8, 0xf7, 0x7a, 0xc5, 0x94, 0x36, 0x8c, 0x9a, 0x8d, 0xec, 0xc3, 0xb6, 0x17, 0xc8, 0x28,
	0x99, 0x98, 0xbd, 0x58, 0xda, 0x2d, 0x93, 0x2a, 0x12, 0x58, 0xe3, 0x99, 0x66, 0x72, 0xc0, 0x12,
	0x4e, 0x35, 0x23, 0x4b, 0xc6, 0xeb, 0xea, 0x8f, 0xd4, 0x4e, 0xff, 0x06, 0xf5, 0x1b, 0x73, 0x2d,
	0x10, 0x58, 0x2b, 0x42, 0x19, 0x21, 0x24, 0x15, 0xdc, 0x00, 0x98, 0xe8, 0x0f, 0xa9, 0x1a, 0x35,
	0xf6, 0x52, 0x42, 0x96, 0x70, 0x0d, 0x9a, 0x85, 0x26, 0x90, 0x9a, 0x09, 0xe8, 0x0e, 0x38, 0xa9,
	0x63, 0x0b, 0x1a, 0x46, 0x3b, 0x15, 0x69, 0x9c, 0xfe, 0x07, 0x60, 0xc5, 0x0b, 0x2b, 0x6e, 0xc3,
	0xe6, 0x38, 0xbe, 0x33, 0x91, 0x0a, 0x1e, 0xc1, 0x63, 0x45, 0xef, 0x79, 0xd6, 0x8f, 0xdc, 0x6a,
	0xa3, 0xd8, 0xed, 0x31, 0x8a, 0x2d, 0x83, 0xa4, 0x8a, 0xeb, 0xd0, 0xb2, 0x17, 0xa8, 0x69, 0xe2,
	0xc8, 0x92, 0x59, 0xa5, 0xfb, 0xb4, 0xf7, 0xa5, 0x22, 0x35, 0xdc, 0x85, 0xad, 0xf8, 0x96, 0xc5,
	0x77, 0x11, 0xcb, 0xee, 0xb9, 0x14, 0xd9, 0x80, 0x65, 0x66, 0x15, 0x3b, 0x40, 0x9c, 0xd9, 0xf4,
	0x2c, 0x91, 0xca, 0x69, 0xcc, 0x48, 0x03, 0x0f, 0x61, 0xaf, 0xcf, 0x32, 0x26, 0xa9, 0x66, 0x91,
	0x63, 0xa0, 0x98, 0x69, 0xd9, 0x70, 0x69, 0xb6, 0x3b, 0xb6, 0xbb, 0x95, 0x90, 0x15, 0x7c, 0x04,
	0xfb, 0xea, 0x76, 0xa8, 0x13, 0xb3, 0xf4, 0x92, 0xb3, 0x89, 0x6d, 0xd8, 0xe9, 0xda, 0x5e, 0xa1,
	0x70, 0x0d, 0xa8, 0xf5, 0xb4, 0x70, 0x0b, 0xd6, 0xdd, 0x0a, 0x86, 0xae, 0xac, 0x09, 0xcc, 0x44,
	0x9a, 0xdd, 0x30, 0x59, 0x45, 0x84, 0x0d, 0x8f, 0x2c, 0x62, 0xac, 0xe1, 0x26, 0xac, 0xc6, 0x22,
	0x1f, 0x15, 0x86, 0x75, 0xb3, 0xdb, 0x02, 0x94, 0x4b, 0x3e, 0xa0, 0x92, 0x33, 0x45, 0x36, 0xcc,
	0x2a, 0x1c, 0x2d, 0xa5, 0xf5, 0x6d, 0xe2, 0x01, 0xec, 0x0e, 0xf3, 0x64, 0x7a, 0xbf, 0x54, 0xd3,
	0x54, 0xf4, 0x09, 0x31, 0xab, 0xf1, 0xae, 0x84, 0x6a, 0x1a, 0x25, 0xbe, 0xd8, 0x4d, 0xc4, 0x2d,
	0x7c, 0x0c, 0xed, 0xd2, 0x38, 0x91, 0xf5, 0xa2, 0x1e, 0x4f, 0x99, 0x22, 0x68, 0x93, 0xe9, 0x97,
	0xa1, 0x9c, 0xea, 0x92, 0xed, 0x69, 0xe3, 0xc0, 0x89, 0x32, 0xd9, 0xc1, 0x3d, 0xc0, 0x84, 0xa5,
	0xcc, 0xc6, 0xe9, 0xa6, 0xcc, 0x26, 0x42, 0x91, 0x5d, 0x0c, 0xe0, 0xc9, 0xd8, 0x3e, 0xbd, 0x64,
	0xbb, 0x96, 0x84, 0x4b, 0x45, 0xf6, 0xcc, 0x1a, 0x3c, 0x46, 0xb1, 0xbe, 0xc9, 0xab, 0x99, 0x4c,
	0x33, 0xeb, 0xdd, 0x37, 0xf9, 0x52, 0x5a, 0xe4, 0xa6, 0x30, 0x22, 0x9a, 0x25, 0x45, 0x45, 0xb4,
	0x4d, 0x92, 0xfd, 0x30, 0x47, 0xdb, 0x78, 0x14, 0x39, 0x30, 0x7b, 0xa6, 0xee, 0x6c, 0x47, 0xa9,
	0xe8, 0xcf, 0xec, 0xf9, 0xd0, 0x0c, 0x94, 0x4c, 0x69, 0x21, 0x59, 0x39, 0x3b, 0x8f, 0x26, 0x0c,
	0x97, 0x3c, 0x8f, 0x4d, 0x4a, 0x8a, 0x51, 0x79, 0xdf, 0x5c, 0x6a, 0x52, 0xa4, 0xe4, 0x33, 0xfc,
	0x0c, 0x0e, 0x24, 0x8b, 0xc5, 0x3d, 0x93, 0x8a, 0x95, 0xcb, 0x9b, 0x3c, 0x31, 0x99, 0x35, 0x67,
	0x20, 0x72, 0x6d, 0x06, 0xf9, 0xdc, 0x24, 0x4a, 0xb2, 0x81, 0xb8, 0x1f, 0xcf, 0x5d, 0x70, 0x78,
	0x84, 0x17, 0xf0, 0xdd, 0x4f, 0x94, 0xeb, 0xa8, 0x27, 0xe4, 0x98, 0x26, 0x2d, 0xa2, 0x2e, 0x8b,
	0x24, 0xa3, 0xc9, 0x28, 0xa2, 0x3d, 0x63, 0xa1, 0x49, 0x62, 0x0e, 0x92, 0x1f, 0x66, 0x29, 0x29,
	0x72, 0xf3, 0x1b, 0xfc, 0x16, 0xbe, 0xf9, 0x84, 0x10, 0x36, 0xe3, 0x26, 0x48, 0x51, 0x24, 0xc1,
	0x98, 0xe5, 0x52, 0x61, 0x1d, 0xe3, 0x39, 0x9c, 0x29, 0xa6, 0x2d, 0xda, 0x77, 0xf2, 0x51, 0xea,
	0x5a, 0xf9, 0x28, 0xa7, 0xfa, 0x36, 0x12, 0x0f, 0x0e, 0xcb, 0x53, 0x3c, 0x83, 0x53, 0x77, 0x24,
	0x68, 0xac, 0x4d, 0x0a, 0x62, 0x91, 0x65, 0xcc, 0x09, 0x9c, 0xc1, 0x97, 0x48, 0xfa, 0xe2, 0xff,
	0xe1, 0x4b, 0xf1, 0x9f, 0xe1, 0x31, 0x7c, 0x3e, 0x3e, 0xde, 0xb6, 0xa6, 0x07, 0xbc, 0x2f, 0xad,
	0x24, 0x46, 0x2a, 0x96, 0x3c, 0xd7, 0x8a, 0x7c, 0x89, 0x27, 0xf0, 0xd4, 0xcb, 0x98, 0x25, 0x5f,
	0x2d, 0x42, 0x9e, 0xe0, 0xd7, 0xf0, 0xbc, 0x40, 0x4e, 0x84, 0x70, 0x11, 0xfc, 0x39, 0xbe, 0x80,
	0x2f, 0x0b, 0x78, 0x21, 0x8d, 0x8b, 0xc0, 0xa7, 0xf8, 0x1c, 0xbe, 0x28, 0xc0, 0x4e, 0x39, 0x17,
	0x41, 0x5f, 0x58, 0x29, 0xb3, 0xaf, 0xab, 0xc8, 0x29, 0x8d, 0xa9, 0xe4, 0xaf, 0x8c, 0xd5, 0x57,
	0xf9, 0xc4, 0xfa, 0xf5, 0xe9, 0x35, 0x2c, 0xfb, 0x87, 0x80, 0x91, 0x93, 0xb1, 0x9e, 0xdb, 0x1a,
	0xab, 0x18, 0x05, 0x97, 0xc3, 0x2c, 0xe3, 0x99, 0x51, 0xd6, 0x35, 0xd3, 0x82, 0x0d, 0x72, 0x13,
	0xc2, 0x5d, 0x09, 0x3d, 0xca, 0x53, 0x96, 0x90, 0x9a, 0x81, 0xa9, 0x3b, 0x9e, 0xe7, 0x2c, 0x21,
	0xf5, 0xf3, 0xff, 0xd6, 0xa0, 0x79, 0x99, 0xf2, 0xf7, 0xa2, 0x33, 0xec, 0xe2, 0xef, 0x01, 0x26,
	0xad, 0x1a, 0xee, 0x3d, 0xe8, 0x5c, 0xed, 0xc5, 0x78, 0xe8, 0xae, 0x66, 0xdf, 0x93, 0x07, 0x95,
	0x97, 0x55, 0xbc, 0x86, 0xfd, 0x05, 0x4f, 0x45, 0x3c, 0x2e, 0x05, 0x99, 0xf7, 0x90, 0x9c, 0x13,
	0xf1, 0x25, 0xac, 0xf8, 0x8e, 0x0b, 0xb7, 0x67, 0x1b, 0xdf, 0x45, 0x23, 0xce, 0xa1, 0x59, 0x74,
	0x5a, 0xb8, 0x53, 0x6a, 0x74, 0x17, 0x8d, 0x39, 0x83, 0x65, 0xd7, 0x86, 0x20, 0xce, 0xf4, 0xb5,
	0x8b, 0xf0, 0x7f, 0x84, 0xd6, 0xf8, 0xfa, 0x47, 0xd7, 0x4d, 0x97, 0xdb, 0x86, 0xc3, 0xed, 0xb2,
	0xd9, 0xbc, 0x9b, 0x2a, 0xf8, 0xda, 0x3c, 0x2a, 0xa7, 0xde, 0x8a, 0x78, 0x50, 0xbc, 0x33, 0x1e,
	0xbc, 0x2b, 0x0f, 0xf7, 0xe7, 0xb9, 0x5c, 0x98, 0x57, 0xb0, 0x36, 0xfd, 0x4a, 0xc4, 0xb6, 0x7f,
	0xdd, 0x3d, 0x78, 0x4f, 0x1e, 0xee, 0xcd, 0xf1, 0xd8, 0x18, 0xdd, 0x65, 0xfb, 0x67, 0xc9, 0x37,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x75, 0x1a, 0xde, 0xd5, 0x40, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CliToHubClient is the client API for CliToHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CliToHubClient interface {
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error)
	InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error)
	Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (CliToHub_RevertClient, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error)
	StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error)
}

type cliToHubClient struct {
	cc *grpc.ClientConn
}

func NewCliToHubClient(cc *grpc.ClientConn) CliToHubClient {
	return &cliToHubClient{cc}
}

func (c *cliToHubClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[0], "/idl.CliToHub/Initialize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[1], "/idl.CliToHub/InitializeCreateCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeCreateClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeCreateClusterClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeCreateClusterClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeCreateClusterClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[2], "/idl.CliToHub/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_ExecuteClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubExecuteClient struct {
	grpc.ClientStream
}

func (x *cliToHubExecuteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[3], "/idl.CliToHub/Finalize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubFinalizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_FinalizeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubFinalizeClient struct {
	grpc.ClientStream
}

func (x *cliToHubFinalizeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (CliToHub_RevertClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[4], "/idl.CliToHub/Revert", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubRevertClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_RevertClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubRevertClient struct {
	grpc.ClientStream
}

func (x *cliToHubRevertClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error) {
	out := new(RestartAgentsReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/RestartAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error) {
	out := new(StopServicesReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/StopServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CliToHubServer is the server API for CliToHub service.
type CliToHubServer interface {
	Initialize(*InitializeRequest, CliToHub_InitializeServer) error
	InitializeCreateCluster(*InitializeCreateClusterRequest, CliToHub_InitializeCreateClusterServer) error
	Execute(*ExecuteRequest, CliToHub_ExecuteServer) error
	Finalize(*FinalizeRequest, CliToHub_FinalizeServer) error
	Revert(*RevertRequest, CliToHub_RevertServer) error
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	RestartAgents(context.Context, *RestartAgentsRequest) (*RestartAgentsReply, error)
	StopServices(context.Context, *StopServicesRequest) (*StopServicesReply, error)
}

// UnimplementedCliToHubServer can be embedded to have forward compatible implementations.
type UnimplementedCliToHubServer struct {
}

func (*UnimplementedCliToHubServer) Initialize(req *InitializeRequest, srv CliToHub_InitializeServer) error {
	return status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (*UnimplementedCliToHubServer) InitializeCreateCluster(req *InitializeCreateClusterRequest, srv CliToHub_InitializeCreateClusterServer) error {
	return status.Errorf(codes.Unimplemented, "method InitializeCreateCluster not implemented")
}
func (*UnimplementedCliToHubServer) Execute(req *ExecuteRequest, srv CliToHub_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedCliToHubServer) Finalize(req *FinalizeRequest, srv CliToHub_FinalizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (*UnimplementedCliToHubServer) Revert(req *RevertRequest, srv CliToHub_RevertServer) error {
	return status.Errorf(codes.Unimplemented, "method Revert not implemented")
}
func (*UnimplementedCliToHubServer) GetConfig(ctx context.Context, req *GetConfigRequest) (*GetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedCliToHubServer) RestartAgents(ctx context.Context, req *RestartAgentsRequest) (*RestartAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartAgents not implemented")
}
func (*UnimplementedCliToHubServer) StopServices(ctx context.Context, req *StopServicesRequest) (*StopServicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServices not implemented")
}

func RegisterCliToHubServer(s *grpc.Server, srv CliToHubServer) {
	s.RegisterService(&_CliToHub_serviceDesc, srv)
}

func _CliToHub_Initialize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Initialize(m, &cliToHubInitializeServer{stream})
}

type CliToHub_InitializeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_InitializeCreateCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeCreateClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).InitializeCreateCluster(m, &cliToHubInitializeCreateClusterServer{stream})
}

type CliToHub_InitializeCreateClusterServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeCreateClusterServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeCreateClusterServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Execute(m, &cliToHubExecuteServer{stream})
}

type CliToHub_ExecuteServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubExecuteServer struct {
	grpc.ServerStream
}

func (x *cliToHubExecuteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Finalize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FinalizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Finalize(m, &cliToHubFinalizeServer{stream})
}

type CliToHub_FinalizeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubFinalizeServer struct {
	grpc.ServerStream
}

func (x *cliToHubFinalizeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Revert_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RevertRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Revert(m, &cliToHubRevertServer{stream})
}

type CliToHub_RevertServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubRevertServer struct {
	grpc.ServerStream
}

func (x *cliToHubRevertServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_RestartAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).RestartAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/RestartAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).RestartAgents(ctx, req.(*RestartAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StopServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StopServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/StopServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StopServices(ctx, req.(*StopServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CliToHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.CliToHub",
	HandlerType: (*CliToHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _CliToHub_GetConfig_Handler,
		},
		{
			MethodName: "RestartAgents",
			Handler:    _CliToHub_RestartAgents_Handler,
		},
		{
			MethodName: "StopServices",
			Handler:    _CliToHub_StopServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Initialize",
			Handler:       _CliToHub_Initialize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitializeCreateCluster",
			Handler:       _CliToHub_InitializeCreateCluster_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _CliToHub_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Finalize",
			Handler:       _CliToHub_Finalize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Revert",
			Handler:       _CliToHub_Revert_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cli_to_hub.proto",
}
