// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package idl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_unknown_mode Mode = 0
	Mode_copy         Mode = 1
	Mode_link         Mode = 2
)

var Mode_name = map[int32]string{
	0: "unknown_mode",
	1: "copy",
	2: "link",
}

var Mode_value = map[string]int32{
	"unknown_mode": 0,
	"copy":         1,
	"link":         2,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type ClusterDestination int32

const (
	ClusterDestination_unknown_destination ClusterDestination = 0
	ClusterDestination_source              ClusterDestination = 1
	ClusterDestination_intermediate        ClusterDestination = 2
	ClusterDestination_target              ClusterDestination = 3
)

var ClusterDestination_name = map[int32]string{
	0: "unknown_destination",
	1: "source",
	2: "intermediate",
	3: "target",
}

var ClusterDestination_value = map[string]int32{
	"unknown_destination": 0,
	"source":              1,
	"intermediate":        2,
	"target":              3,
}

func (x ClusterDestination) String() string {
	return proto.EnumName(ClusterDestination_name, int32(x))
}

func (ClusterDestination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type Segment_Role int32

const (
	Segment_unknown_role Segment_Role = 0
	Segment_primary      Segment_Role = 1
	Segment_mirror       Segment_Role = 2
)

var Segment_Role_name = map[int32]string{
	0: "unknown_role",
	1: "primary",
	2: "mirror",
}

var Segment_Role_value = map[string]int32{
	"unknown_role": 0,
	"primary":      1,
	"mirror":       2,
}

func (x Segment_Role) String() string {
	return proto.EnumName(Segment_Role_name, int32(x))
}

func (Segment_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0, 0}
}

type Segment struct {
	DbID                 int32        `protobuf:"varint,1,opt,name=dbID,proto3" json:"dbID,omitempty"`
	ContentID            int32        `protobuf:"varint,2,opt,name=contentID,proto3" json:"contentID,omitempty"`
	Role                 Segment_Role `protobuf:"varint,3,opt,name=role,proto3,enum=idl.Segment_Role" json:"role,omitempty"`
	Port                 int32        `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Hostname             string       `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DataDir              string       `protobuf:"bytes,6,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (m *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(m, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetDbID() int32 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *Segment) GetContentID() int32 {
	if m != nil {
		return m.ContentID
	}
	return 0
}

func (m *Segment) GetRole() Segment_Role {
	if m != nil {
		return m.Role
	}
	return Segment_unknown_role
}

func (m *Segment) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Segment) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Segment) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type Cluster struct {
	Destination          ClusterDestination `protobuf:"varint,1,opt,name=destination,proto3,enum=idl.ClusterDestination" json:"destination,omitempty"`
	GpHome               string             `protobuf:"bytes,2,opt,name=gpHome,proto3" json:"gpHome,omitempty"`
	Version              string             `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Coordinator          *Segment           `protobuf:"bytes,4,opt,name=coordinator,proto3" json:"coordinator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetDestination() ClusterDestination {
	if m != nil {
		return m.Destination
	}
	return ClusterDestination_unknown_destination
}

func (m *Cluster) GetGpHome() string {
	if m != nil {
		return m.GpHome
	}
	return ""
}

func (m *Cluster) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Cluster) GetCoordinator() *Segment {
	if m != nil {
		return m.Coordinator
	}
	return nil
}

func init() {
	proto.RegisterEnum("idl.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("idl.ClusterDestination", ClusterDestination_name, ClusterDestination_value)
	proto.RegisterEnum("idl.Segment_Role", Segment_Role_name, Segment_Role_value)
	proto.RegisterType((*Segment)(nil), "idl.Segment")
	proto.RegisterType((*Cluster)(nil), "idl.Cluster")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x41, 0xcb, 0xd3, 0x40,
	0x10, 0xfd, 0x36, 0x49, 0x93, 0x76, 0x52, 0xca, 0xba, 0x82, 0x0d, 0xe2, 0xa1, 0x14, 0x84, 0x52,
	0x24, 0x60, 0x3d, 0x79, 0x36, 0x07, 0x7b, 0xf0, 0x12, 0x0f, 0x1e, 0x25, 0xcd, 0x2e, 0x75, 0x69,
	0x76, 0x27, 0x4c, 0xb6, 0x8a, 0x7f, 0xc8, 0xbf, 0xe5, 0x5f, 0x91, 0xdd, 0xa6, 0x36, 0xe2, 0x6d,
	0x5e, 0xde, 0xe4, 0xcd, 0x7b, 0x8f, 0x85, 0x65, 0x8b, 0xc6, 0xa0, 0x2d, 0x7b, 0x42, 0x87, 0x22,
	0xd6, 0xb2, 0xdb, 0xfe, 0x66, 0x90, 0x7d, 0x56, 0x67, 0xa3, 0xac, 0x13, 0x02, 0x12, 0x79, 0x3a,
	0x56, 0x05, 0xdb, 0xb0, 0xdd, 0xac, 0x0e, 0xb3, 0x78, 0x05, 0x8b, 0x16, 0xad, 0x53, 0xd6, 0x1d,
	0xab, 0x22, 0x0a, 0xc4, 0xe3, 0x83, 0x78, 0x0d, 0x09, 0x61, 0xa7, 0x8a, 0x78, 0xc3, 0x76, 0xab,
	0xc3, 0xb3, 0x52, 0xcb, 0xae, 0x1c, 0xd5, 0xca, 0x1a, 0x3b, 0x55, 0x07, 0xda, 0x0b, 0xf7, 0x48,
	0xae, 0x48, 0x6e, 0xc2, 0x7e, 0x16, 0x2f, 0x61, 0xfe, 0x0d, 0x07, 0x67, 0x1b, 0xa3, 0x8a, 0xd9,
	0x86, 0xed, 0x16, 0xf5, 0x5f, 0x2c, 0x0a, 0xc8, 0x64, 0xe3, 0x9a, 0x4a, 0x53, 0x91, 0x06, 0xea,
	0x0e, 0xb7, 0x6f, 0x21, 0xf1, 0xba, 0x82, 0xc3, 0xf2, 0x6a, 0x2f, 0x16, 0x7f, 0xd8, 0xaf, 0xfe,
	0x02, 0x7f, 0x12, 0x39, 0x64, 0x3d, 0x69, 0xd3, 0xd0, 0x4f, 0xce, 0x04, 0x40, 0x6a, 0x34, 0x11,
	0x12, 0x8f, 0xb6, 0xbf, 0x18, 0x64, 0x1f, 0xba, 0xeb, 0xe0, 0x14, 0x89, 0xf7, 0x90, 0x4b, 0x35,
	0x38, 0x6d, 0x1b, 0xa7, 0xd1, 0x86, 0xa0, 0xab, 0xc3, 0x3a, 0xd8, 0x1e, 0x57, 0xaa, 0x07, 0x5d,
	0x4f, 0x77, 0xc5, 0x0b, 0x48, 0xcf, 0xfd, 0x47, 0x34, 0x2a, 0xb4, 0xb0, 0xa8, 0x47, 0xe4, 0xbd,
	0x7e, 0x57, 0x34, 0x78, 0xb9, 0xf8, 0xe6, 0x75, 0x84, 0xa2, 0x84, 0xbc, 0x45, 0x24, 0xe9, 0x15,
	0x90, 0x42, 0xf8, 0xfc, 0xb0, 0x9c, 0x76, 0x54, 0x4f, 0x17, 0xf6, 0x6f, 0x20, 0xf9, 0x84, 0xf2,
	0x9f, 0x6c, 0x06, 0xa5, 0xcf, 0x36, 0x87, 0xa4, 0xc5, 0xde, 0x07, 0x9b, 0x43, 0xd2, 0x69, 0x7b,
	0xe1, 0xd1, 0xfe, 0x0b, 0x88, 0xff, 0x2d, 0x8b, 0x35, 0x3c, 0xbf, 0xff, 0x3b, 0x31, 0xcf, 0x9f,
	0x7c, 0x23, 0x03, 0x5e, 0xa9, 0x55, 0x9c, 0xf9, 0x03, 0xda, 0x3a, 0x45, 0x46, 0x49, 0xdd, 0x38,
	0xc5, 0x23, 0xcf, 0xba, 0x86, 0xce, 0xca, 0xf1, 0xf8, 0x94, 0x86, 0xd7, 0xf1, 0xee, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0xd0, 0xe7, 0xe3, 0x2d, 0x02, 0x00, 0x00,
}
