// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package idl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_unknown_mode Mode = 0
	Mode_copy         Mode = 1
	Mode_link         Mode = 2
)

var Mode_name = map[int32]string{
	0: "unknown_mode",
	1: "copy",
	2: "link",
}

var Mode_value = map[string]int32{
	"unknown_mode": 0,
	"copy":         1,
	"link":         2,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type ClusterDestination int32

const (
	ClusterDestination_unknown_destination ClusterDestination = 0
	ClusterDestination_source              ClusterDestination = 1
	ClusterDestination_intermediate        ClusterDestination = 2
	ClusterDestination_target              ClusterDestination = 3
)

var ClusterDestination_name = map[int32]string{
	0: "unknown_destination",
	1: "source",
	2: "intermediate",
	3: "target",
}

var ClusterDestination_value = map[string]int32{
	"unknown_destination": 0,
	"source":              1,
	"intermediate":        2,
	"target":              3,
}

func (x ClusterDestination) String() string {
	return proto.EnumName(ClusterDestination_name, int32(x))
}

func (ClusterDestination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func init() {
	proto.RegisterEnum("idl.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("idl.ClusterDestination", ClusterDestination_name, ClusterDestination_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xcd, 0xaa, 0xc2, 0x40,
	0x0c, 0x85, 0xfb, 0x47, 0xb9, 0x84, 0x2e, 0x42, 0xee, 0xc2, 0x77, 0x28, 0xe2, 0xc6, 0x47, 0xd0,
	0xad, 0x6b, 0x97, 0x52, 0x3b, 0x41, 0x42, 0x3b, 0x49, 0x99, 0xa6, 0x88, 0x6f, 0x2f, 0x23, 0x88,
	0xbb, 0xc3, 0x39, 0x1c, 0xbe, 0x0f, 0xba, 0xd1, 0x62, 0x34, 0x3d, 0x2c, 0xc9, 0xdc, 0xa8, 0x96,
	0x30, 0xf7, 0x7b, 0x68, 0x2e, 0x16, 0x98, 0x10, 0xba, 0x4d, 0x27, 0xb5, 0xa7, 0xde, 0xa2, 0x05,
	0xc6, 0x82, 0xfe, 0xa0, 0x19, 0x6d, 0x79, 0x61, 0x99, 0xd3, 0x2c, 0x3a, 0x61, 0xd5, 0x5f, 0x81,
	0x4e, 0xf3, 0xb6, 0x3a, 0xa7, 0x33, 0xaf, 0x2e, 0x3a, 0xb8, 0x98, 0xd2, 0x0e, 0xfe, 0xbf, 0xdf,
	0xf0, 0xab, 0xb1, 0x20, 0x80, 0x76, 0xb5, 0x2d, 0x8d, 0x8c, 0x65, 0x06, 0x88, 0x3a, 0xa7, 0xc8,
	0x41, 0x06, 0x67, 0xac, 0xf2, 0xea, 0x43, 0x7a, 0xb0, 0x63, 0x7d, 0x6f, 0x3f, 0x4a, 0xc7, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0x38, 0x7e, 0x28, 0xa2, 0x00, 0x00, 0x00,
}
